inherit_from: .rubocop_todo.yml

require: 
  - rubocop-rspec
  - rubocop-other-extension
  - rubocop-performance
  
AllCops:
  Include:
    - rubocop-rspec
  Exclude:
    - 'bin/bundle'

  Rails:
    Enabled: true

  Rails/UnknownEnv:
    Environments:
      - production
      - staging
      - development
      - test